name: ✨ Feature Request
description: Suggest a new feature or enhancement for PoliSim
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve PoliSim! Please describe your feature request in detail.

  - type: checkboxes
    id: existing-check
    attributes:
      label: Pre-submission Checklist
      description: Please verify these before submitting
      options:
        - label: I have searched existing issues/discussions and this feature has not been requested
          required: true
        - label: This feature aligns with PoliSim's mission of policy simulation and analysis
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Policy Domain (e.g., immigration, trade, defense)
        - Simulation Enhancement (accuracy, performance, scenarios)
        - API Enhancement (new endpoints, better responses)
        - Dashboard/UI Improvement
        - Data Integration (new data sources, CBO updates)
        - Developer Experience (tooling, testing, docs)
        - Educational Feature (tutorials, teaching mode)
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: |
        Currently, PoliSim cannot...
        Users need to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: |
        I propose adding...
        This would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of PoliSim would this affect?
      options:
        - Simulation Engine (core/)
        - Policy Parser/Extractor
        - API Server
        - Dashboard/UI
        - MCP Server
        - Documentation
        - Multiple Components
        - New Component
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be used
      placeholder: |
        1. A researcher wants to...
        2. A policymaker needs to...
        3. A student is learning about...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have ideas on how this could be implemented, share them here
      placeholder: |
        Technical approach:
        - Step 1...
        - Step 2...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in helping implement this?
      options:
        - label: I would be willing to contribute to implementing this feature
        - label: I can provide domain expertise or data sources
        - label: I can help test this feature once implemented

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical for my use case
    validations:
      required: true
